### ISSUE TITLE
Crear Clase product_dao

### ISSUE THREAD

**Issue by matias9486** [CodeSystem2022/ERROR-404_Proyecto_3S#5]
- Importar las clases necesarias.
- Crear la clase product_dao.
- Definir las consultas requeridas para realizar un CRUD en postgres.
- Debe tener los siguientes métodos de clase: seleccionar, insertar, actualizar y eliminar. Los últimos tres métodos reciben producto como parámetro.

**Comment by MalsinaG** [comment]
se completa la clase product_dao y se cierra el issue
